# Generated by Django 5.1.2 on 2024-11-07 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grados',
            name='anual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matricula.anual'),
        ),
        migrations.AddField(
            model_name='grados',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matricula.sede'),
        ),
    ]
