# Generated by Django 5.1.2 on 2024-11-07 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_grados_anual_grados_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grados',
            name='sede',
        ),
        migrations.DeleteModel(
            name='Sede',
        ),
    ]
