# Generated by Django 5.1.2 on 2024-11-07 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0003_remove_grados_sede_delete_sede'),
        ('usuarios', '0006_modulogrupopermiso_sedegp'),
    ]

    operations = [
        migrations.AddField(
            model_name='grados',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.sede'),
        ),
    ]
