# Generated by Django 5.1.2 on 2024-11-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0004_grados_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='grados',
            name='nombre_grado',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
