# Generated by Django 5.1.2 on 2024-11-13 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0005_grados_nombre_grado'),
        ('usuarios', '0006_modulogrupopermiso_sedegp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_diagnostico', to='usuarios.persona')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
