# Generated by Django 5.1.2 on 2024-11-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0006_diagnostico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='descripcion',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
