# Generated by Django 5.1.2 on 2024-11-15 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0008_piar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contextogenaral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripacion', models.TextField(max_length=250, null=True)),
                ('familiar', models.TextField(max_length=250, null=True)),
                ('otros', models.TextField(max_length=250, null=True)),
                ('piar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piar_contexto', to='matricula.piar')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
