# Generated by Django 5.1.2 on 2024-11-18 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0009_contextogenaral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracionpedagogica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competecias', models.TextField(max_length=250, null=True)),
                ('principales', models.TextField(max_length=250, null=True)),
                ('estado', models.TextField(max_length=250, null=True)),
                ('piar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piar_valoracion', to='matricula.piar')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
