# Generated by Django 5.1.2 on 2024-11-19 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0013_objetivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Razonables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajustes', models.TextField(null=True)),
                ('didacticos', models.TextField(null=True)),
                ('evaluacion', models.TextField(null=True)),
                ('adicionales', models.TextField(null=True)),
                ('casa', models.TextField(null=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razonables_materia', to='matricula.materias')),
                ('piar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piar_rasonnables', to='matricula.piar')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
