# Generated by Django 5.1.2 on 2024-11-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0015_piar_createdat_piar_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
