# Generated by Django 5.1.2 on 2024-11-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0016_alter_diagnostico_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='piar',
            name='soporte_pago',
            field=models.FileField(blank=True, null=True, upload_to='PIAR/'),
        ),
    ]
