# Generated by Django 5.1.2 on 2024-11-26 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0017_piar_soporte_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piar',
            old_name='soporte_pago',
            new_name='soporte',
        ),
    ]
