# Generated by Django 5.1.2 on 2024-11-27 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0018_rename_soporte_pago_piar_soporte'),
        ('usuarios', '0012_alter_persona_acudiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='grados',
            name='docenteapoyo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_docenteapoyo', to='usuarios.persona'),
        ),
        migrations.AddField(
            model_name='grados',
            name='docenteorienta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_docenteorienta', to='usuarios.persona'),
        ),
    ]
