# Generated by Django 5.1.2 on 2024-11-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulogrupopermiso',
            name='sedegp',
            field=models.ManyToManyField(related_name='grupos_sede', to='usuarios.sede'),
        ),
    ]
