# Generated by Django 5.1.2 on 2024-11-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_modulogrupopermiso_sedegp'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='rol',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
