# Generated by Django 5.1.2 on 2024-11-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_persona_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='direccion',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='telefono',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
