# Generated by Django 5.1.2 on 2024-11-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_sede_direccion_sede_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='etnia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='victima',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
