# Generated by Django 5.1.2 on 2024-11-20 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_persona_etnia_persona_victima'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['-id']},
        ),
    ]
