# Generated by Django 5.1.2 on 2024-11-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_persona_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='acudiente',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='discapacidad',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
