# Generated by Django 5.1.2 on 2024-11-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_persona_acudiente_persona_discapacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='acudiente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
